export const SHARED_INTERVIEW_LOADING = "SHARED_INTERVIEW_LOADING";
export const SHARED_INTERVIEW_SET_DATA = "SHARED_INTERVIEW_SET_DATA";
export const SHARED_INTERVIEW_SET_DETAILS = "SHARED_INTERVIEW_SET_DETAILS";
export const SHARED_INTERVIEW_SET_BASIC_DETAILS = "SHARED_INTERVIEW_SET_BASIC_DETAILS";